const questions = [
  {
    id: "q1",
    type: "text",
    question_ro: "Cum te numești?",
    question_ru: "Как тебя зовут?",
    required: true,
  },
  {
    id: "q2",
    type: "stars",
    question_ro: "Cât de mulțumit ești de experiența generală?",
    question_ru: "Насколько вы довольны общим опытом?",
    scale: 5,
    required: true,
  },
  {
    id: "q3",
    type: "slider",
    question_ro: "Cât de probabil este să ne recomanzi unui prieten?",
    question_ru: "Какова вероятность, что вы порекомендуете нас другу?",
    min: 0,
    max: 10,
    required: true,
  },
  {
    id: "q4",
    type: "radio",
    question_ro: "Cât de ușor ți-a fost să folosești serviciul nostru?",
    question_ru: "Насколько легко было воспользоваться нашей услугой?",
    options_ro: ["Foarte ușor", "Ușor", "Neutru", "Dificil", "Foarte dificil"],
    options_ru: ["Очень легко", "Легко", "Нейтрально", "Сложно", "Очень сложно"],
    required: true,
  },
  {
    id: "q5",
    type: "radio",
    question_ro: "Care a fost principalul motiv pentru care ai folosit serviciul?",
    question_ru: "Какова была основная причина использования сервиса?",
    options_ro: ["Recomandare", "Publicitate", "Necesitate urgentă", "Curiozitate", "Alt motiv"],
    options_ru: ["Рекомендация", "Реклама", "Срочная необходимость", "Любопытство", "Другое"],
  },
  {
    id: "q6",
    type: "choice",
    question_ro: "Ce aspecte ți-au plăcut cel mai mult?",
    question_ru: "Что вам понравилось больше всего?",
    options_ro: ["Interfață prietenoasă", "Timp de răspuns rapid", "Personal amabil", "Preț avantajos", "Claritate în informații"],
    options_ru: ["Удобный интерфейс", "Быстрый отклик", "Дружелюбный персонал", "Хорошая цена", "Понятная информация"],
  },
  {
    id: "q7",
    type: "choice",
    question_ro: "Unde crezi că putem îmbunătăți?",
    question_ru: "Где, по вашему мнению, мы можем улучшиться?",
    options_ro: ["Timp de răspuns", "Claritate informații", "Navigare aplicație", "Serviciu clienți", "Altceva"],
    options_ru: ["Скорость ответа", "Понятность информации", "Навигация", "Служба поддержки", "Другое"],
  },
  {
    id: "q8",
    type: "textarea",
    question_ro: "Ai sugestii pentru îmbunătățire?",
    question_ru: "Есть предложения по улучшению?",
  },
  {
    id: "q9",
    type: "radio",
    question_ro: "Ai mai folosit acest serviciu înainte?",
    question_ru: "Вы уже пользовались этой услугой ранее?",
    options_ro: ["Da", "Nu"],
    options_ru: ["Да", "Нет"],
    required: true,
  },
  {
    id: "q10",
    type: "stars",
    question_ro: "Cum evaluezi raportul calitate/preț?",
    question_ru: "Как вы оцениваете соотношение цена/качество?",
    scale: 5,
  },
];

export default questions;